version: 2.1

commands:
  install_deps:
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  run_linter:
    steps:
      - checkout
      - run: npm run lint
  run_test:
    steps:
      - checkout
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  build_electron_pkg:
    steps:
      - checkout
      - run:
          name: build electron package
          command: ./scripts/electron-build.sh

executors:
  my-executor:
    docker:
      - image: 'circleci/node:erbium'
    working_directory: /tmp

jobs:
  lint-and-test:
    docker:
      - image: circleci/node:erbium-browsers
    steps:
      - install_deps
      - run_linter
      - run_test
  build_packages:
    docker:
      - image: circleci/node:erbium
    steps:
      - install_deps
      - run_linter
      - build_electron_pkg
      - persist_to_workspace:
          root: ~/
          paths:
            - project/dist

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/project/dist
      - run:
          name: 'Publish Release on GitHub'
          command: |
            if [ "$(ls -A ~/project/dist/)" ]
            then
              ls -alh ~/project/dist/
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ~/project/dist/
            else
              echo "No files found"
            fi

workflows:
  lint-and-test:
    jobs:
      - lint-and-test:
          filters:
            branches:
              ignore: /.*/
  build-and-release:
    jobs:
      - build_packages:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^saza-v.*/
      - publish-github-release:
          requires:
            - build_packages
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^saza-v.*/
