version: 2.1

commands:
  install_deps:
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  run_linter:
    steps:
      - checkout
      - run: npm run lint
  run_test:
    steps:
      - checkout
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  build_electron_pkg:
    steps:
      - checkout
      - run:
          name: build electron package
          command: ./scripts/electron-build.sh

orbs:
  node: circleci/node@1.1.6
jobs:
  lint-and-test:
    docker:
      - image: circleci/node:erbium-browsers
    steps:
      - install_deps
      - run_linter
      - run_test
  build_packages:
    docker:
      - image: circleci/node:erbium
    steps:
      - install_deps
      - run_linter
      - build_electron_pkg
      - persist_to_workspace:
          paths:
            - dist
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./dist
      - run:
          name: 'Publish Release on GitHub'
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./dist/

workflows:
  lint-and-test:
    jobs:
      - lint-and-test
  build-and-release:
    jobs:
      - build_packages
      - publish-github-release:
          requires:
            - build_packages
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^saza-v*/
