version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: circleci/node:erbium-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
workflows:
  build-and-test:
    jobs:
      - build-and-test
